#!/bin/bash
i=0

# EC2 instance settings
AMI=ami-051f8a213df8bc089
IAM_PROFILE=S3EC2
REGION=us-east-1
SUBNET=subnet-019702dbe48e89a8b

# Loop through each instance type in the instance-type file
while read instance_type
do
    # Print the instance type
    echo $instance_type

    # Start the instance
    aws ec2 run-instances --instance-type $instance_type --image-id $AMI --count 1 --iam-instance-profile Name=$IAM_PROFILE --instance-initiated-shutdown-behavior terminate --user-data file://userdata --region $REGION --subnet-id $SUBNET
    i=$(($i + 1))

    # Sleep for 30 minutes after 5 instances
    n=$(($i % 5))
    if [ $n -eq 0 ]
    then
        echo "Sleeping for 30 minutes"
        sleep 1800
    fi
done < instance-type

